package open.com.model.type;

public enum JobType {

	RETIRED ,
	STUDENT , 
	PHARMACEUTICAL ,
	INSURANCE , 
    FINANCIALSERVICE, 
    TELECOMUNICATION, 
    SCIENTIFIC ,  
    CONSTRUCTION, 
    FOODANDBEVERAGE , 
    WOODANDPAPER, 
    RETAILTRADE, 
    ACCOMODATIONANDFOODSERVICES
}
